# action name
name: 'publish-binaries'

# action description
description: 'Adds docker-cli and docker-compose binaries to releases.'

# action input values
inputs:
  TRIGGER_TAG:
    description: 'The tag for the release'
    required: true
runs:
  using: 'docker'
  image: '.github/Dockerfile'
  args:
      - ${{ inputs.TRIGGER_TAG }}
